language: go
notifications:
  email: false
branches:
  only:
    - master
before_install:
    - export PATH=$HOME/gopath/bin:$PATH
after_failure:
  - "cat /home/travis/build/alphagov/performanceplatform-organisation-api/error.log"
